fix(metrics): use official lowlighter/metrics action
The Heroku instance has a bug in the base plugin:
TypeError: Cannot read properties of undefined (reading 'repositories')

Reverting to the official action which is properly maintained.